### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by zadilkhwaja** [ummadiviany/Awesome-Internships#2]
IIT(ISM) Dhanbad link not working.

PS: Thankyou so much i was able to get summer internship at IIT Indore through this list!!

**Comment by ummadiviany** [comment]
Hi @zadilkhwaja, Happy to hear this repo is useful for you. Congratulations for your summer internship @ IIT Indore!!!
About ISM Dhanbad , this is from 2020 so the I guess the link might have scraped by admins.
